import { FormEvent, useEffect, useRef, useState } from "react";
import type { ConnectionState, HarnessApi, ProviderProfile, Task, TaskEvent, TaskState, Workspace } from "./types";

interface AppProps { api: HarnessApi; }
const STATUS: Partial<Record<TaskState, string>> = { WAITING_PLAN_APPROVAL: "⏸ 等待计划批准", DECIDING: "↻ 等待运行", WAITING_ACTION_APPROVAL: "⚠ 等待危险动作处理", EXECUTING: "↻ 正在执行", WAITING_FINAL_REVIEW: "✓ 等待最终审查", WAITING_USER: "⚠ 等待用户处理", COMPLETED: "✓ 已完成" };
const text = (value: unknown): string | undefined => typeof value === "string" ? value : undefined;
const display = (value: unknown): string | undefined => typeof value === "string" || typeof value === "number" ? String(value) : undefined;
const object = (value: unknown): Record<string, unknown> | undefined => typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
const latestEvent = (events: TaskEvent[], matches: (event: TaskEvent) => boolean): TaskEvent | undefined => events.filter(matches).sort((left, right) => right.sequence - left.sequence || Date.parse(right.occurred_at) - Date.parse(left.occurred_at))[0];
const hasChangedPaths = (event: TaskEvent): boolean => { const changedPaths = object(event.payload.result)?.changed_paths; return Array.isArray(changedPaths) && changedPaths.length > 0; };
const completeDiagnostic = (payload: Record<string, unknown> | undefined): string | undefined => {
  if (!payload) return undefined;
  const diagnostic = text(payload.diagnostic); const digest = text(payload.content_sha256); const bytes = payload.content_bytes;
  if (!diagnostic?.trim() || diagnostic.startsWith("[OUTPUT_LIMIT ") || !digest || !/^[0-9a-f]{64}$/.test(digest) || !Number.isInteger(bytes) || bytes !== new TextEncoder().encode(diagnostic).length) return undefined;
  return diagnostic;
};

export function App({ api }: AppProps) {
  const [projectPath, setProjectPath] = useState(""); const [requirement, setRequirement] = useState("");
  const [workspace, setWorkspace] = useState<Workspace>(); const [task, setTask] = useState<Task>(); const [events, setEvents] = useState<TaskEvent[]>([]); const [stateUnknown, setStateUnknown] = useState(false);
  const [providers, setProviders] = useState<ProviderProfile[]>([]); const [providerKind, setProviderKind] = useState<ProviderProfile["kind"]>("deepseek"); const [providerModel, setProviderModel] = useState("deepseek-chat"); const [providerId, setProviderId] = useState(""); const [apiKey, setApiKey] = useState("");
  const [connection, setConnection] = useState<ConnectionState>("disconnected"); const [message, setMessage] = useState("请接入本地 Git 项目后建立信任。"); const [busy, setBusy] = useState<string>();
  const lastSequence = useRef(0); const taskId = task?.id;
  useEffect(() => { if (api.listProviders) void api.listProviders().then(setProviders).catch(() => setProviders([])); }, [api]);
  useEffect(() => { if (!taskId) return; let active = true; lastSequence.current = 0; const reconcileInvalidEvent = (): void => { setEvents([]); lastSequence.current = 0; setStateUnknown(true); setMessage("事件数据无效，已清空审批证据并正在与服务对账。"); void api.getTask(taskId).then((current) => { if (active) { setTask(current); setStateUnknown(false); setMessage("任务状态已对账；请等待完整审批证据重新到达。"); } }).catch(() => { if (active) setMessage("事件数据无效且状态对账失败；请重新接入项目。"); }); }; const stop = api.subscribeEvents(taskId, 0, { onEvent: (next) => { if (next.sequence > lastSequence.current) { lastSequence.current = next.sequence; setEvents((current) => [...current, next]); } }, onConnection: setConnection, onInvalidEvent: reconcileInvalidEvent }); return () => { active = false; stop(); }; }, [api, taskId]);
  const run = async (key: string, action: () => Promise<void>, settleTaskId?: string): Promise<void> => { if (busy) return; setBusy(key); try { await action(); } catch { if (settleTaskId) { try { setTask(await api.getTask(settleTaskId)); } catch { setTask(undefined); setEvents([]); lastSequence.current = 0; setStateUnknown(true); } } setMessage("无法完成此操作。请检查服务状态后重试。"); } finally { setBusy(undefined); } };
  const connectProject = (form: FormEvent): void => { form.preventDefault(); void run("project", async () => { setWorkspace(undefined); setTask(undefined); setEvents([]); lastSequence.current = 0; setStateUnknown(false); setApiKey(""); const created = await api.connectProject(projectPath); setWorkspace(created); setMessage("项目已接入，请审阅摘要并显式建立信任。"); }); };
  const createTask = (form: FormEvent): void => { form.preventDefault(); if (!workspace) return; void run("task", async () => { const created = await api.createTask(workspace.id, requirement, providerId || undefined); setEvents([]); setTask(created); setApiKey(""); setMessage("计划已生成，等待计划事件到达。"); }); };
  const configureProvider = (form: FormEvent): void => { form.preventDefault(); const createProvider = api.createProvider; const setSessionCredential = api.setSessionCredential; if (!createProvider || !setSessionCredential || !apiKey) return; void run("provider", async () => { try { const profile = await createProvider(providerKind, providerModel); const configured = await setSessionCredential(profile.id, apiKey); setProviders((current) => [...current, configured]); setProviderId(configured.id); } finally { setApiKey(""); } }); };
  const plan = latestEvent(events, (event) => event.event_type === "PLAN_PROPOSED"); const planDiagnostic = completeDiagnostic(plan?.payload);
  const latestChange = latestEvent(events, (event) => event.event_type === "TOOL_EXECUTION_COMPLETED" && hasChangedPaths(event));
  const verification = latestEvent(events, (event) => event.event_type === "VERIFICATION_SUCCEEDED" && (latestChange === undefined || event.sequence > latestChange.sequence)); const verificationRun = verification && object(verification.payload.run); const verificationDiagnostic = verificationRun?.ok === true ? text(verificationRun.diagnostic) : undefined;
  const starts = new Map([...events].sort((left, right) => left.sequence - right.sequence || Date.parse(left.occurred_at) - Date.parse(right.occurred_at)).filter((event) => event.event_type === "TOOL_EXECUTION_STARTED").map((event) => [text(event.payload.execution_id), object(event.payload.action)]));
  const diff = latestEvent(events, (event) => event.event_type === "TOOL_EXECUTION_COMPLETED" && (latestChange === undefined || event.sequence > latestChange.sequence) && text(starts.get(text(event.payload.execution_id) ?? "")?.tool) === "git_diff"); const diffDiagnostic = diff && completeDiagnostic(object(diff.payload.result));
  const finalSummary = latestEvent(events, (event) => event.event_type === "FINAL_SUMMARY_PROPOSED" && event.sequence > (diff?.sequence ?? Number.MAX_SAFE_INTEGER) && event.sequence > (verification?.sequence ?? Number.MAX_SAFE_INTEGER)); const finalDiagnostic = finalSummary && completeDiagnostic(finalSummary.payload);
  const approvals = Array.from(new Map(events.filter((event) => event.event_type === "GOVERNANCE_BLOCKED" || event.state_after === "WAITING_ACTION_APPROVAL").map((event) => { const reason = text(event.payload.reason_code) ?? "未提供原因"; const scope = text(event.payload.normalized_scope) ?? "未提供精确范围"; return [`${reason}:${scope}`, { reason, scope }]; })).values());
  const status = task ? STATUS[task.state] ?? `● ${task.state}` : "○ 尚未创建任务"; const lastEvent = events.at(-1);
  const mutationDisabled = busy !== undefined || stateUnknown || (task !== undefined && connection !== "connected");
  const showPlanApproval = !stateUnknown && task?.state === "WAITING_PLAN_APPROVAL" && planDiagnostic !== undefined;
  const showRun = !stateUnknown && task?.state === "DECIDING";
  const showFinalApproval = !stateUnknown && task?.state === "WAITING_FINAL_REVIEW" && verificationDiagnostic !== undefined && !verificationDiagnostic.startsWith("[OUTPUT_LIMIT ") && diffDiagnostic !== undefined && finalDiagnostic !== undefined;

  return <main className="app-shell" aria-busy={busy !== undefined}>
    <header><p className="eyebrow">本地 Coding Agent Harness</p><h1>受治理的编码任务工作台</h1><p className="status" aria-live="polite">{status} · SSE：{connection === "connected" ? "● 已连接" : connection === "reconnecting" ? "↻ 正在重连" : "○ 未连接"}</p><p className="message" role="status">{message}</p></header>
    <section aria-labelledby="project-heading"><h2 id="project-heading">项目接入</h2><form onSubmit={connectProject}><label htmlFor="project-path">项目路径</label><div className="inline-form"><input id="project-path" value={projectPath} onChange={(event) => setProjectPath(event.target.value)} required /><button type="submit" disabled={busy !== undefined}>{busy === "project" ? "正在接入" : "接入项目"}</button></div></form>{workspace && <div className="summary" aria-live="polite"><p>{workspace.languages.join(", ") || "未识别语言"} · {workspace.default_branch}</p><p>已跟踪 {workspace.repository?.tracked_count ?? 0} 项，测试 {workspace.repository?.test_count ?? 0} 项，未提交变更 {workspace.repository?.dirty_count ?? 0} 项。</p>{workspace.repository?.test_paths?.length ? <p>测试位置：{workspace.repository.test_paths.join(", ")}</p> : null}{!workspace.trusted ? <button type="button" disabled={mutationDisabled} onClick={() => void run("trust", async () => { setWorkspace(await api.trustProject(workspace)); setMessage("已建立当前项目配置的信任。"); })}>{busy === "trust" ? "正在建立信任" : "建立信任"}</button> : <p>✓ 当前项目已建立信任</p>}</div>}</section>
    {api.createProvider && api.setSessionCredential && <section aria-labelledby="provider-heading"><h2 id="provider-heading">Provider</h2><form onSubmit={configureProvider}><label htmlFor="provider-kind">类型</label><select id="provider-kind" value={providerKind} onChange={(event) => setProviderKind(event.target.value as ProviderProfile["kind"])}><option value="deepseek">deepseek</option><option value="qwen">qwen</option></select><label htmlFor="provider-model">模型</label><input id="provider-model" value={providerModel} onChange={(event) => setProviderModel(event.target.value)} required /><label htmlFor="provider-key">API Key</label><input id="provider-key" type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} required /><button type="submit" disabled={busy !== undefined}>{busy === "provider" ? "正在配置" : "配置会话 Provider"}</button></form><label htmlFor="provider-profile">已配置 Profile</label><select id="provider-profile" value={providerId} onChange={(event) => setProviderId(event.target.value)}><option value="">请选择</option>{providers.filter((item) => item.configured).map((item) => <option key={item.id} value={item.id}>{item.kind}: {item.model}</option>)}</select></section>}
    <section aria-labelledby="requirement-heading"><h2 id="requirement-heading">需求输入</h2><form onSubmit={createTask}><label htmlFor="requirement">编码需求</label><textarea id="requirement" value={requirement} onChange={(event) => setRequirement(event.target.value)} required /><button type="submit" disabled={!workspace?.trusted || mutationDisabled}>{busy === "task" ? "正在生成" : "生成计划"}</button></form></section>
    <section aria-labelledby="plan-heading"><h2 id="plan-heading">计划审批</h2>{planDiagnostic ? <><pre>{planDiagnostic}</pre><p>摘要：{text(plan?.payload.content_sha256) ?? "未提供"}（{display(plan?.payload.content_bytes) ?? "未提供"} bytes）</p></> : plan ? <p>计划内容不完整，无法审批；请重新运行以取得完整计划。</p> : <p>尚未收到可审阅计划。</p>}{showPlanApproval && <button type="button" disabled={mutationDisabled} onClick={() => task && void run("approve-plan", async () => { const approved = await api.approvePlan(task.id); setTask(approved); setTask(await api.runTask(task.id)); setMessage("计划已批准，任务已触发运行。"); }, task.id)}>{busy === "approve-plan" ? "正在批准" : "批准计划"}</button>}{showRun && <button type="button" disabled={mutationDisabled} onClick={() => task && void run("run", async () => { setTask(await api.runTask(task.id)); }, task.id)}>{busy === "run" ? "正在运行" : "继续运行"}</button>}</section>
    <section aria-labelledby="timeline-heading"><h2 id="timeline-heading">事件时间线</h2><p aria-live="polite">{connection === "reconnecting" ? "↻ 事件流断开，正在重连。" : `○ ${lastEvent ? `新事件 #${lastEvent.sequence} ${lastEvent.event_type}` : "事件按序号续传。"}`}</p><ol>{events.map((event) => <li key={event.sequence}><strong>#{event.sequence} {event.event_type}</strong></li>)}</ol></section>
    <section aria-labelledby="approval-heading"><h2 id="approval-heading">危险动作审批</h2>{approvals.length === 0 ? <p>当前没有待审批危险动作。<span>后端尚无可提交操作</span>。</p> : <div role="alert">{approvals.map((approval) => <article key={`${approval.reason}:${approval.scope}`} className="approval"><p>原因：{approval.reason}</p><p>精确范围：{approval.scope}</p><p>后端尚无可提交操作。</p></article>)}</div>}</section>
    <section aria-labelledby="review-heading"><h2 id="review-heading">测试与最终审查</h2><p>{verificationDiagnostic ? <>✓ <span>测试已通过</span>：<span>{verificationDiagnostic}</span></> : "○ 等待测试结果"}</p>{task?.state === "WAITING_FINAL_REVIEW" && !showFinalApproval ? <p>终审证据不完整，需等待当前轮次的完整差异、最终摘要和验证结果。</p> : null}{showFinalApproval && <button type="button" disabled={mutationDisabled} onClick={() => task && void run("approve-final", async () => { setTask(await api.approveFinal(task.id)); setMessage("已提交最终审查批准。"); }, task.id)}>{busy === "approve-final" ? "正在批准" : "批准最终审查"}</button>}<h2>最终差异</h2><pre>{diffDiagnostic ?? "尚无差异摘要。"}</pre><h2>最终摘要</h2><pre>{finalDiagnostic ?? "尚无最终摘要。"}</pre></section>
  </main>;
}
